# which simulation parameters are integers (the rest are floats)
INTEGER_SIMULATION_PARAMETERS:
    - N_tot
    - N_init
    - algo
    - make_random_initial_infections # 1 = True, 0 = False
    - N_connect_retries
    - event_size_max

# exclude these parameters in network initialization filename
EXCLUDE_PARAMETER_IN_INIT:
    - N_init
    - lambda_E
    - lambda_I
    - make_random_initial_infections
    - event_size_max