name: NetworkSIR
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - iminuit
  - statsmodels
  - jupyter
  - jupyterlab
  - tqdm
  - pyyaml
  - black
  - pysftp
  - numba/label/dev::numba
  - icc_rt
  - joblib
  - scikit-learn # uses ParameterSampler to fit multiple times
  - psutil
  # - datashader
  - awkward
  - pyarrow
  - pytables
  - astropy
  - imageio-ffmpeg
  - h5py
  - pathos
  - geopandas
  - descartes
  - tinydb
  # - p_tqdm
  - pip:
    - mpl-scatter-density
    - pygifsicle
    - contexttimer
    - awkward1>=0.2.32
    - range-key-dict
    - p_tqdm