name: NetworkSIR
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8  
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - iminuit
  - statsmodels
  - jupyter
  - jupyterlab
  - tqdm
  - pyyaml
  - black
  - pysftp
  - plotly
  # - numba
  - numba/label/dev::numba
  - joblib
  - scikit-learn
  - psutil
  - plotly-orca
  #- natsort
  - datashader
  - awkward
  - pyarrow
  - networkx
  - fast-histogram
  - astropy
  - imageio-ffmpeg
  - pip:
    - mpl-scatter-density
    - pygifsicle